apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ipob56kv7-nodejs
  janus-idp.io/tekton: ipob56kv7-nodejs
  backstage.io/kubernetes-id: ipob56kv7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ipob56kv7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
